# Generated by Django 5.1.4 on 2025-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising_app', '0002_alter_donation_donation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='raised_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
