# Generated by Django 5.1.4 on 2025-03-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising_app', '0003_alter_cause_raised_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
