# Generated by Django 5.1.4 on 2025-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising_app', '0004_donation_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
