# Generated by Django 5.1.4 on 2025-03-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising_app', '0005_alter_donation_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('stopped', 'Stopped')], default='active', max_length=10),
        ),
    ]
